services:
  nginx:
    image: nginx:alpine
    container_name: memos-nginx
    restart: unless-stopped
#    ports:
#      - "${APP_PORT:-80}:80"
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - 'memnode:/var/www/html/node_modules'
#      - 'memvendor:/var/www/html/vendor'  # Add for consistency
      - 'mem-sockets:/run/php'  # Shared socket volume
    depends_on:
      - php84
    networks:
      - fit-network
      - proxy-network
    environment:
      - VIRTUAL_HOST=memberos.localhost,*.memberos.localhost
      - VIRTUAL_PORT=80
  php84:
    build:
      context: .
      dockerfile: ./docker/php84/Dockerfile.php84
    image: memos-php84
    container_name: memos-php84
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      XDEBUG_MODE: '${MEM_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${MEM_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
      - 'memnode:/var/www/html/node_modules'
#      - 'memvendor:/var/www/html/vendor'
      - 'mem-sockets:/run/php'  # Shared socket volume
    working_dir: /var/www/html
    networks:
      - fit-network
    depends_on:
      pgsql:
        condition: service_started
      redis:
        condition: service_started
  pgsql:
    build:
      context: .
      dockerfile: ./docker/pgsql/Dockerfile.pgsql
    container_name: memos-pgsql
    platform: linux/amd64
    image: 'postgres:17-bookworm-custom'
    ports:
      - '127.0.0.1:5402:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - './docker/pgsql/init-extensions.sql:/docker-entrypoint-initdb.d/05-init-extensions.sql'
    networks:
      - fit-network
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  redis:
    image: redis:latest
    container_name: memos-redis
#    ports:
#      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fit-network
networks:
  fit-network:
    driver: bridge
  proxy-network:
    external: true
volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local
  memnode:
#  memvendor:
  mem-sockets: