services:
  nginx:
    image: nginx:alpine
    container_name: g2arms-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - '.:/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
      - 'sailnode:/var/www/html/node_modules'
      - 'sailvendor:/var/www/html/vendor'  # Add for consistency
      - 'sail-sockets:/run/php'  # Shared socket volume
    depends_on:
      - php84
    networks:
      - sail
  php84:
    build:
      context: .
      dockerfile: ./docker/php84/Dockerfile.php84
    image: g2arms-php84
    container_name: g2arms-php84
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
      - 'sailnode:/var/www/html/node_modules'
      - 'sailvendor:/var/www/html/vendor'
      - 'sail-sockets:/run/php'  # Shared socket volume
    working_dir: /var/www/html
    networks:
      - sail
    depends_on:
      pgsql:
        condition: service_started
      redis:
        condition: service_started
      twpreview:
        condition: service_completed_successfully
  pgsql:
    build:
      context: .
      dockerfile: ./docker/pgsql/Dockerfile.pgsql
    container_name: g2arms-pgsql
    platform: linux/amd64
    image: 'postgres:17-bookworm-custom'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - './docker/pgsql/init-extensions.sql:/docker-entrypoint-initdb.d/05-init-extensions.sql'
    networks:
      - sail
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
  redis:
    image: redis:latest
    container_name: g2arms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sail
  twpreview:
    build:
      context: './vendor/laravel/sail/runtimes/8.4'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        NODE_VERSION: '20'
    working_dir: /var/www/html
    container_name: g2arms-tw
    volumes:
      - ./:/var/www/html
    entrypoint:
      - bash
      - -lc
      - >
        cp /var/www/html/docker/twpreview/init.sh /tmp/tw_init.sh &&
        chmod 0755 /tmp/tw_init.sh &&
        /bin/bash /tmp/tw_init.sh
    user: "root"
    restart: "no"
networks:
  sail:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  redis-data:
    driver: local
  sailnode:
  sailvendor:
  sail-sockets: